---
title: "Lab 04 - La Quinta is Spanish for next to Denny's, Pt. 2"
author: "Rachel Good"
date: "`r Sys.Date()`"
output: github_document
---

### Load packages and data

```{r load-packages, message = FALSE}
library(tidyverse) 
library(dsbox) 
library(dplyr)
```

```{r load-data, message = FALSE}
states <- read_csv("data/states.csv")
```

```{r upload_datasets}
data(dennys)
data(laquinta)
```

### Exercise 1

```{r filter_dataframe_dennys_AK}
dn_ak <- dennys %>% 
  filter(state == "AK")
nrow(dn_ak)
```
### Exercise 2

```{r filter_dataframe_laquinta_AK}
lq_ak <- laquinta %>% 
  filter(state == "AK")
nrow(lq_ak)
```
### Exercise 3

```{r joining_dataframes}
dn_lq_ak <- full_join(dn_ak, lq_ak, by = "state")
dn_lq_ak
```

### Exercise 4
There are 6 observations in the dn_lq_ak data frame. The variables are: .x[address, city, state, zip, longitude, latitude] and .y[address, city, zip, longitude, latitude]


### Exercise 5

```{r create_haversine_function}
haversine <- function(long1, lat1, long2, lat2, round = 3) {
  # convert to radians
  long1 = long1 * pi / 180
  lat1  = lat1  * pi / 180
  long2 = long2 * pi / 180
  lat2  = lat2  * pi / 180
  
  R = 6371 # Earth mean radius in km
  
  a = sin((lat2 - lat1)/2)^2 + cos(lat1) * cos(lat2) * sin((long2 - long1)/2)^2
  d = R * 2 * asin(sqrt(a))
  
  return( round(d,round) ) # distance in km
}
```



### Exercise 6

```{r calculating_distance}
dn_lq_ak <- dn_lq_ak %>% 
  mutate(distance = haversine(longitude.x, latitude.x, longitude.y, latitude.y, round = 3))
```

### Exercise 7

```{r minimum_distance}
dn_lq_ak_mindist <- dn_lq_ak %>%
  group_by(address.x) %>%
  summarize(closest = min(distance))
```

### Exercise 8

```{r distribution}
library(forcats)
dn_lq_ak_mindist %>% 
  mutate(address.x = fct_reorder(address.x, closest)) %>% 
ggplot(dn_lq_ak_mindist, mapping = aes(x = address.x, y = closest)) +
  geom_col()
```

### Exercise 9

```{r NC_analysis}

```
